### ISSUE TITLE
Not an issue but idk how to contact you in any other way

### ISSUE THREAD

**Issue by kitsunesvensson** [sakurasort/sakurasort.github.io#1]
Could you make one of those top-lists sorters that you did for SG members, but for BM songs from both albums instead? I'd be really thankful.

**Comment by sakurasort** [comment]
Yeah this is the intended way to contact me.

I added this feature in 5bcb08a24879094418627025fd474247567b3189, you can find the page at http://sakurasort.github.io/bmsong.html
